import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";

export default defineConfig({
    plugins: [
        laravel({
            input: [
                "resources/components/Footer.js",
                "resources/components/Header.js",
                "resources/css/bookman-old-style.css",
                "resources/css/home.css",
                "resources/css/index.css",
                "resources/css/style.css",
                "resources/js/fetch.js",
                "resources/js/index.js",
                "resources/js/mapTrends.js",
                "resources/js/script.js",
                "resources/js/seasonalTrend.js",
                "resources/js/sendConcern.js",
                "resources/js/soilHealth.js",
                "resources/js/statistics.js",
                "resources/js/topCrops.js",
                "resources/js/weatherForecast.js",
                "resources/management/components/HeaderSidebar.js",
                "resources/management/components/classes/Barangay.js",
                "resources/management/components/classes/Crop.js",
                "resources/management/components/classes/CropVariety.js",
                "resources/management/components/classes/Damage.js",
                "resources/management/components/classes/Disease.js",
                "resources/management/components/classes/Farmer.js",
                "resources/management/components/classes/Pest.js",
                "resources/management/components/classes/Price.js",
                "resources/management/components/classes/Production.js",
                "resources/management/components/classes/Record.js",
                "resources/management/components/classes/RiceProduction.js",
                "resources/management/components/classes/SoilHealth.js",
                "resources/management/components/helpers/deleteModal.js",
                "resources/management/components/helpers/Dialog.js",
                "resources/management/components/helpers/editModal.js",
                "resources/management/components/pages/Concerns.js",
                "resources/management/components/pages/Dashboard.js",
                "resources/management/components/pages/DataEntries.js",
                "resources/management/components/pages/DataEntriesMenu.js",
                "resources/management/components/pages/Maintenance.js",
                "resources/management/components/pages/MaintenanceMenu.js",
                "resources/management/components/pages/ManageUsers.js",
                "resources/management/css/dialog.css",
                "resources/management/css/index.css",
                "resources/management/css/login.css",
                "resources/management/js/admin.js",
                "resources/management/js/index.js",
                "resources/management/js/login.js",
                "resources/management/img/loginBg.png",
                "resources/management/img/logo.png",
                "resources/img/weather/clear.jpeg",
                "resources/img/weather/cloudy.jpeg",
                "resources/img/weather/day.jpeg",
                "resources/img/weather/night.jpeg",
                "resources/img/weather/rain.jpeg",
                "resources/img/weather/storm.jpeg",
                "resources/img/CAO-1.png",
                "resources/img/CAO-logo.png",
                "resources/img/contact.png",
                "resources/img/header1.png",
                "resources/img/logo.png",
                "resources/img/seasonaltrends.png",
                "resources/img/underline1.png",
            ],
            refresh: true,
        }),
    ],
});
